# Generated by Django 3.0.4 on 2020-04-03 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_posting',
            name='type',
            field=models.CharField(choices=[('1', 'Womenswear'), ('2', 'Menswear'), ('3', 'Accesories'), ('4', 'Footwear')], max_length=1),
        ),
    ]
