# Generated by Django 3.0.5 on 2020-04-07 21:35

from django.db import migrations, models
import selling.models


class Migration(migrations.Migration):

    dependencies = [
        ('selling', '0002_auto_20200403_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_posting',
            name='image',
            field=models.FileField(blank=True, upload_to=selling.models.get_upload_path),
        ),
    ]
