# Generated by Django 3.0.5 on 2020-04-15 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selling', '0004_auto_20200407_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_posting',
            name='image',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='item_posting',
            name='image2',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='item_posting',
            name='image3',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='item_posting',
            name='image4',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
